import prettier from 'eslint-config-prettier';
import path from 'node:path';
import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import { defineConfig, includeIgnoreFile } from 'eslint/config';
import globals from 'globals';
import ts from 'typescript-eslint';

const gitignorePath = path.resolve(import.meta.dirname, '.gitignore');

export default defineConfig(
	includeIgnoreFile(gitignorePath),
	// Generated by `wrangler types` — not project source.
	{ ignores: ['worker-configuration.d.ts'] },
	// Vendored, pinned Sveltia CMS bundle (self-hosted third-party minified build,
	// refreshed via `npm run cms:sync`) — not project source, do not lint.
	{ ignores: ['static/admin/sveltia-cms.js'] },
	js.configs.recommended,
	ts.configs.recommended,
	svelte.configs.recommended,
	prettier,
	svelte.configs.prettier,
	{
		languageOptions: { globals: { ...globals.browser, ...globals.node } },
		rules: {
			// typescript-eslint strongly recommend that you do not use the no-undef lint rule on TypeScript projects.
			// see: https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
			'no-undef': 'off'
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser
			}
		}
	},
	{
		// Override or add rule settings here, such as:
		// 'svelte/button-has-type': 'error'
		rules: {
			// The site deploys at the domain root (Cloudflare Pages: *.pages.dev →
			// zlobekstromiec.pl), so there is no configured `base` path and
			// `resolve()` base-prefixing is a no-op. Internal section routes are
			// also built incrementally across Plans 04–05 of this phase, so typing
			// `resolve('/aktualnosci' | …)` against not-yet-generated route IDs would
			// break the phased build. Plain absolute internal hrefs are correct here.
			'svelte/no-navigation-without-resolve': 'off'
		}
	}
);
