#!/usr/bin/env node
/**
 * cms:sync -- keeps the self-hosted Sveltia admin assets in lockstep with the
 * pinned @sveltia/cms npm package.
 *
 * 1. Copies dist/sveltia-cms.js byte-identical (pinning policy T-0204-01).
 * 2. Regenerates static/admin/locale-pl.js from locales/pl.json plus the
 *    package version. The bundle's locale cache check requires an exact
 *    version match; an upgrade without regeneration would silently fall back
 *    to the CSP-blocked unpkg fetch and the chrome would revert to English.
 * 3. Copies the Nunito woff2 files referenced by static/admin/admin.css.
 * 4. Fails loudly if the vendored Material Symbols woff2 is missing (one-time
 *    manual download, committed to the repo; see admin.css).
 */
import { copyFileSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkgDir = join(root, 'node_modules', '@sveltia', 'cms');
const adminDir = join(root, 'static', 'admin');
const fontsDir = join(adminDir, 'fonts');

const { version } = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8'));

copyFileSync(join(pkgDir, 'dist', 'sveltia-cms.js'), join(adminDir, 'sveltia-cms.js'));

const strings = JSON.parse(readFileSync(join(pkgDir, 'locales', 'pl.json'), 'utf8'));
const banner =
	'// GENERATED by scripts/cms-sync.mjs -- do not edit by hand.\n' +
	`// Source: @sveltia/cms@${version} locales/pl.json. Consumed by preboot.js.\n`;
writeFileSync(
	join(adminDir, 'locale-pl.js'),
	`${banner}window.__SVELTIA_LOCALE_PL__ = ${JSON.stringify({ version, strings })};\n`
);

for (const f of [
	'nunito-latin-400-normal.woff2',
	'nunito-latin-700-normal.woff2',
	'nunito-latin-ext-400-normal.woff2',
	'nunito-latin-ext-700-normal.woff2'
]) {
	copyFileSync(join(root, 'node_modules', '@fontsource', 'nunito', 'files', f), join(fontsDir, f));
}

const icons = join(fontsDir, 'material-symbols-outlined-latin-wght-normal.woff2');
if (!existsSync(icons)) {
	console.error('cms:sync: missing vendored icon font at', icons);
	console.error(
		'Download once from https://cdn.jsdelivr.net/fontsource/fonts/material-symbols-outlined:vf@5.3.1/latin-wght-normal.woff2 and commit it.'
	);
	process.exit(1);
}

console.log(`cms:sync: bundle + pl locale + fonts synced (@sveltia/cms@${version})`);
