// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces
declare global {
	namespace App {
		interface Platform {
			// Phase 1 consumes no secrets. `Env` is generated by `wrangler types`
			// from wrangler.jsonc (empty now). Phase 4 adds RESEND_API_KEY and
			// TURNSTILE_SECRET_KEY as Cloudflare bindings → they surface here.
			env: Env;
			ctx: ExecutionContext;
			caches: CacheStorage;
			cf?: IncomingRequestCfProperties;
		}

		// interface Error {}
		// interface Locals {}
		// interface PageData {}
		// interface PageState {}
	}
}

export {};
