// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces
declare global {
	// Secrets and plain vars that never appear in wrangler.jsonc, so `wrangler types`
	// cannot generate them. They are declared here and merge into the generated global
	// `Env` interface (worker-configuration.d.ts). All optional on purpose: a missing
	// binding must be a type-level possibility the endpoint handles explicitly, not a
	// runtime surprise (FORM-01/FORM-02, 04-RESEARCH.md §Environment Availability).
	// FORMS_KV is deliberately NOT redeclared here: it comes from wrangler.jsonc via
	// `wrangler types`, and a duplicate declaration risks a merge conflict.
	interface Env {
		/** Resend API key. Cloudflare Pages secret; absent locally unless set in .dev.vars. */
		RESEND_API_KEY?: string;
		/** Turnstile secret for server-side siteverify. Never the sitekey. */
		TURNSTILE_SECRET_KEY?: string;
		/** Secret salt for the rate-limit key hash, so the hash is not rainbow-tableable. */
		RATE_LIMIT_SALT?: string;
		/** Submissions allowed per client per hour, base-10 string. Unset in production. */
		RATE_LIMIT_MAX?: string;
		/** '1' short-circuits the Resend send. ONLY ever set in the gitignored .dev.vars. */
		FORM_DRY_RUN?: string;
	}

	namespace App {
		interface Platform {
			// Phase 1 consumed no secrets. `Env` is generated by `wrangler types` from
			// wrangler.jsonc and surfaced here. Phase 4 (Plan 04-01) added the FORMS_KV
			// namespace binding via wrangler.jsonc plus the five form vars declared
			// above: RESEND_API_KEY, TURNSTILE_SECRET_KEY, RATE_LIMIT_SALT,
			// RATE_LIMIT_MAX and FORM_DRY_RUN.
			env: Env;
			ctx: ExecutionContext;
			caches: CacheStorage;
			cf?: IncomingRequestCfProperties;
		}

		// interface Error {}
		// interface Locals {}
		// interface PageData {}
		// interface PageState {}
	}
}

export {};
